// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3YgqrMLxwxt2T7DhsRSd_n3R5AMv1WzE',
    appId: '1:1075601648196:web:233e2b1290323f9eb5aa11',
    messagingSenderId: '1075601648196',
    projectId: 'udemy-3d9ed',
    authDomain: 'udemy-3d9ed.firebaseapp.com',
    storageBucket: 'udemy-3d9ed.firebasestorage.app',
    measurementId: 'G-KDQGT7SNCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkNsFwXGaO9QadyK6vJubVJbRbm6iZfxY',
    appId: '1:1075601648196:android:cab49571504c2f82b5aa11',
    messagingSenderId: '1075601648196',
    projectId: 'udemy-3d9ed',
    storageBucket: 'udemy-3d9ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAFIxKrZd9WKlOCBI9GbWPADSCAg6J914',
    appId: '1:1075601648196:ios:4f095b66988a2f25b5aa11',
    messagingSenderId: '1075601648196',
    projectId: 'udemy-3d9ed',
    storageBucket: 'udemy-3d9ed.firebasestorage.app',
    iosClientId: '1075601648196-c26nmrna971ph8n5lq15v1fddevb1996.apps.googleusercontent.com',
    iosBundleId: 'com.example.udemyflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAFIxKrZd9WKlOCBI9GbWPADSCAg6J914',
    appId: '1:1075601648196:ios:4f095b66988a2f25b5aa11',
    messagingSenderId: '1075601648196',
    projectId: 'udemy-3d9ed',
    storageBucket: 'udemy-3d9ed.firebasestorage.app',
    iosClientId: '1075601648196-c26nmrna971ph8n5lq15v1fddevb1996.apps.googleusercontent.com',
    iosBundleId: 'com.example.udemyflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3YgqrMLxwxt2T7DhsRSd_n3R5AMv1WzE',
    appId: '1:1075601648196:web:32be12667bbf8117b5aa11',
    messagingSenderId: '1075601648196',
    projectId: 'udemy-3d9ed',
    authDomain: 'udemy-3d9ed.firebaseapp.com',
    storageBucket: 'udemy-3d9ed.firebasestorage.app',
    measurementId: 'G-G4R531VLEX',
  );
}
